version: "3.9"
services:                                      
  docker_jenkins:
    environment:
      - TZ=Asia/Shanghai
    user: root                                
    restart: always                          
    image: jenkins/jenkins:lts               
    container_name: cicd-jenkins                
    ports:                                   
      - 8077:8080                             
      - 50000:50000                          
    volumes:                                
      - ./jenkins/jenkins_home/:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker            
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
  docker_nginx:
    environment:
      - TZ=Asia/Shanghai
    restart: always
    image: nginx:stable-alpine                
    container_name: cicd-nginx
    ports:
      - 7070:80                             
    volumes:
      - ./nginx/:/etc/nginx/conf.d/  
      - ./webserver/static/jenkins/dist/:/usr/share/nginx/html/ 